language: go

go:
    - "1.15.x"

before_install:
  # https://github.com/travis-ci/travis-ci/issues/8361
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

script:
- make install
- make test
- make smoke
- git clone https://github.com/oragono/irctest && cd irctest && make integration
